name: MLOps Continuous Training (CT) Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 
  repository_dispatch:
    types: [grafana-alert-drift, grafana-alert-accuracy] 
  schedule:
    - cron: '0 0 * * 0' 

jobs:
  continuous-training:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Tahap 1 - Automated Testing
      run: |
        pytest tests/

    - name: Tahap 2, 3, & 4 - Server MLflow, Training, & Evaluasi
      run: |
        rm -f mlflow.db

        nohup mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 127.0.0.1 --port 5000 --workers 1 > /dev/null 2>&1 &
        
        sleep 5
        
        echo "Memulai Proses Training..."
        python src/intelligence/train.py --n_estimators 100 --max_depth 10
        
        echo "Memulai Proses Evaluasi Komparatif..."
        python src/intelligence/evaluate_and_register.py